# Generated by Django 4.1 on 2022-09-22 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=35)),
                ('doctor_service', models.CharField(max_length=25)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_days', models.CharField(max_length=15)),
                ('available_time', models.TimeField(max_length=15)),
                ('doctor_email', models.EmailField(max_length=50)),
                ('doctor_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=35)),
                ('service_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=35)),
                ('reviews', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=35)),
                ('select_service', models.CharField(max_length=100)),
                ('select_doctor', models.CharField(max_length=100)),
                ('select_days', models.CharField(max_length=15)),
                ('select_date', models.DateField(max_length=15)),
                ('patient_email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_appointment.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_appointment.service'),
        ),
    ]
