# Generated by Django 4.1 on 2022-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_appointment', '0002_alter_doctor_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(max_length=25),
        ),
    ]
